apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.b.volume.name }}
  name: {{ .Values.b.volume.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.b.volume.resources.requests.storage }}
