apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: booking-service
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - booking-gateway
  http:
    - route:
        - destination:
            host: booking-service-grpc-v1
          weight: 90
        - destination:
            host: booking-service-grpc-v2
          weight: 10