replicaCount: 1

image:
  name: booking-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80 # Grpc services for .net run on 9090
  targetPort: 8080

resources:

readinessProbe:
  enabled: true
  httpGet:
    path: /ping
    port: 8080
  failureThreshold: 15
  periodSeconds: 10
  
livenessProbe:
  enabled: true
  httpGet:
    path: /ping
    port: 8080
  failureThreshold: 1
  periodSeconds: 10


