services:
  booking-service:
    image: booking-service-grpc:1.0.0
    container_name: booking-service-test
    environment:
      DATABASE_HOST: bookingservicegrpc-db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: hotelio
      DATABASE_PASSWORD: hotelio
      DATABASE_NAME: db
      HOTEL_HOST: http://host.docker.internal:8084/api/hotels/
      PROMO_CODE_HOST: http://host.docker.internal:8084/api/promos/
      REVIEW_HOST: http://host.docker.internal:8084/api/reviews/
      USER_API_HOST: http://host.docker.internal:8084/api/users/
      KAFKA_HOST: PLAINTEXT://host.docker.internal:9092
    networks:
      - booking-net
      - hotelio-net
    ports:
      - "9090:8081"
      - "80:8080"
    depends_on:
      - bookingservicegrpc-db
    
  bookingservicegrpc-db:
    image: postgres:17
    pull_policy: missing
    container_name: booking-service-db-test
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hotelio -P hotelio -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - bookingservicegrpc-db-data-test:/var/lib/postgresql/data  
    networks:
      - booking-net
      - hotelio-net
    ports:
      - "5433:5432"

networks:
  booking-net:
    driver: bridge
  hotelio-net:
    external: true
volumes:
  bookingservicegrpc-db-data-test:
  

